- name: Deployed Web server
  hosts: web
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
    - name: Install multiple pkgs
      yum:
        name:
          - git
          - tree
        state: present
    - name: Remove Apache
      yum:
        name: httpd
        state: absent