- hosts: web
  become: yes
  vars:
    port: 80
    domain: 3.111.246.69
    docroot: /usr/share/nginx/html

  tasks:
    - name: Enable NGINX in Amazon Linux Extras
      command: amazon-linux-extras enable nginx1

    - name: Clean metadata cache
      command: yum clean metadata

    - name: Ensure nginx installed
      yum:
        name: nginx
        state: present
      tags: nginx_install  

    - name: Remove default nginx config file
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      tags: nginx_rm
    - name: Ensure nginx installed
      yum:
        name: nginx
        state: absent
      tags: nginx_remove

    - name: Deploy custom nginx config
      template:
        src: nginx.j2
        dest: /etc/nginx/conf.d/app1.conf

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
        enabled: yes
